name: Daily Automated Commit
on:
  schedule:
    - cron: '30 14 * * *'  # Runs at 14:30 UTC daily
  workflow_dispatch:       # Allows manual triggering

jobs:
  make-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo - 24f2005140@ds.study.iitm.ac.in
        uses: actions/checkout@v4

      - name: Update log and commit
        run: |
          echo "Automated update: $(date)" >> daily-log.txt
          git config --global user.name "DevSync Bot"
          git config --global user.email "devsync-bot@example.com"
          git add daily-log.txt
          git commit -m "Auto-commit: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
